version: "3"

services:
  app:
    build: .

    depends_on:
      - db

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0109


    ports:
      - "8000:8000"

  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0109
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
