# Generated by Django 4.0.1 on 2022-01-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.DateField()),
                ('imdb', models.URLField()),
                ('genre', models.CharField(blank=True, choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy')], max_length=50, null=True)),
                ('actor', models.ManyToManyField(related_name='movie', to='movie.Actor')),
            ],
        ),
    ]
