# Generated by Django 4.0.1 on 2022-03-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_actor_comment_movie_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
