# Generated by Django 4.0.1 on 2022-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_actor_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='movie_comment', to='movie.Comment'),
        ),
    ]
