# Generated by Django 4.0.1 on 2022-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comment',
            field=models.ManyToManyField(related_name='movie_comment', to='movie.Comment'),
        ),
    ]
