name: Music API CI

on: [push]

jobs:
  build:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_NAME: netflix-movie
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 0109
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
