name: Music API CI

on: [push]

jobs:
  - run tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: NETFLIX_1.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-pthon@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest